package ca.bnc.qe.veritas.codegen;

import ca.bnc.qe.veritas.engine.model.ApiModel;
import ca.bnc.qe.veritas.engine.model.Endpoint;
import org.springframework.stereotype.Component;

/**
 * Emits an IntelliJ HTTP Client / Bruno-compatible {@code .http} file — one request per extracted endpoint —
 * for ad-hoc API checks (the bank-approved alternative). Fully deterministic from the AST {@link ApiModel};
 * no LLM. {@code {{baseUrl}}} and {@code {{token}}} resolve from the http-client env file.
 */
@Component
public class HttpRequestsEmitter {

    public String emit(String serviceName, ApiModel code) {
        StringBuilder sb = new StringBuilder();
        sb.append("### ").append(serviceName).append(" — ad-hoc API requests (IntelliJ HTTP Client / Bruno)\n");
        sb.append("# Set {{baseUrl}} and {{token}} in http-client.env.json. Generated by Veritas from the code.\n\n");
        if (code.endpoints() != null) {
            for (Endpoint e : code.endpoints()) {
                String m = e.method() != null ? e.method().name() : "GET";
                String path = e.pathTemplate() == null ? "/" : e.pathTemplate();
                sb.append("### ").append(m).append(' ').append(path).append('\n');
                sb.append(m).append(" {{baseUrl}}").append(path).append('\n');
                sb.append("Accept: application/json\n");
                if (e.security() != null && !e.security().isEmpty()) {
                    sb.append("Authorization: Bearer {{token}}\n");
                }
                if (m.equals("POST") || m.equals("PUT") || m.equals("PATCH")) {
                    sb.append("Content-Type: application/json\n\n{\n  \n}\n");
                }
                sb.append('\n');
            }
        }
        return sb.toString();
    }
}
