package ca.bnc.qe.veritas.defect;

import static org.assertj.core.api.Assertions.assertThat;

import ca.bnc.qe.veritas.config.ConnectionsProperties;
import ca.bnc.qe.veritas.integration.jira.JiraCreateRequest;
import ca.bnc.qe.veritas.persistence.FindingRecord;
import org.junit.jupiter.api.Test;

/** Server/DC edition → the defect description is wiki markup with {code} blocks (reference template). */
class DefectComposerWikiTest {

    private DefectComposer serverComposer() {
        ConnectionsProperties c = new ConnectionsProperties();
        c.getJira().setEdition("SERVER_DC");
        return new DefectComposer(c);
    }

    @Test
    void emitsWikiCodeBlocksForYamlAndSnippet() {
        FindingRecord f = new FindingRecord();
        f.setType("STATUS_CODE_MISSING");
        f.setEndpoint("GET /policies");
        f.setSeverity("MAJOR");
        f.setLayer("L4");
        f.setSummary("Spec omits 404");
        f.setCodeFile("PolicyController.java");
        f.setCodeStartLine(45);
        f.setCodeSnippet("return ResponseEntity.notFound().build();");
        f.setCurrentYamlFragment("  /policies:\n    get: {}");
        f.setProposedFix("  /policies:\n    get:\n      responses:\n        '404': {}");
        f.setCitation("CTFL 2.2");

        JiraCreateRequest req = serverComposer().compose(f, "ciam-policies", "CIAM", null);
        String desc = String.join("\n\n", req.descriptionParagraphs());

        assertThat(desc).contains("h3. Code Evidence");
        assertThat(desc).contains("{code:java}").contains("ResponseEntity.notFound");
        assertThat(desc).contains("h3. Current YAML").contains("{code:yaml}");
        assertThat(desc).contains("h3. Proposed Fix (Corrected YAML)");
        assertThat(desc).contains("Generated by Veritas Contract Validation Agent");
    }
}
