package ca.bnc.qe.veritas.codegen;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import ca.bnc.qe.veritas.secret.SecretProvider;
import ca.bnc.qe.veritas.vcs.GitHost;
import ca.bnc.qe.veritas.vcs.RepoInfo;
import org.eclipse.jgit.api.Git;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Exercises the full JGit publish path (branch → commit → push) against a local bare remote — no network,
 * no credentials — and verifies the PR is opened via the {@link GitHost} with the pushed branch.
 */
class PrPublisherTest {

    @Test
    void pushesBranchToRemoteAndOpensPr(@TempDir Path tmp) throws Exception {
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();

        Path work = tmp.resolve("work");
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString())
                .setDirectory(work.toFile()).call()) {
            Files.writeString(work.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }

        // a generated test file the publisher should commit
        Files.writeString(work.resolve("GeneratedApiTest.java"), "class GeneratedApiTest {}");

        String[] capturedBranch = new String[1];
        GitHost host = new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) {
                return List.of();
            }
            public List<String> listBranches(String appId, String repoSlug) {
                return List.of();
            }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) {
                return null;
            }
            public String openPullRequest(String repoSlug, String sourceBranch, String targetBranch,
                                          String title, String description) {
                capturedBranch[0] = sourceBranch;
                return "https://bitbucket.org/bnc/" + repoSlug + "/pull-requests/1";
            }
        };
        SecretProvider secrets = key -> Optional.empty();

        PrPublisher publisher = new PrPublisher(host, secrets);
        PrPublisher.PrResult result = publisher.publish(new PrPublisher.PrRequest(
                work, "ciam-policies-tests", "veritas/generated-tests", "main",
                "Add generated API tests", "Generated by Veritas", "test: add generated API tests"));

        assertThat(result.branch()).isEqualTo("veritas/generated-tests");
        assertThat(result.prUrl()).contains("/pull-requests/1");
        assertThat(capturedBranch[0]).isEqualTo("veritas/generated-tests");

        // the branch must exist on the bare remote
        try (Git origin = Git.open(bare.toFile())) {
            boolean pushed = origin.branchList().call().stream()
                    .anyMatch(r -> r.getName().equals("refs/heads/veritas/generated-tests"));
            assertThat(pushed).isTrue();
        }
    }

    @Test
    void returnsThePushedBranchAsABreadcrumbWhenOpeningThePrFails(@TempDir Path tmp) throws Exception {
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        Path work = tmp.resolve("work");
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(work.toFile()).call()) {
            Files.writeString(work.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }
        Files.writeString(work.resolve("GeneratedApiTest.java"), "class GeneratedApiTest {}");

        GitHost host = new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) { return List.of(); }
            public List<String> listBranches(String appId, String repoSlug) { return List.of(); }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) { return null; }
            public String openPullRequest(String r, String s, String t, String ti, String d) {
                throw new IllegalStateException("Bitbucket PR creation failed");   // push succeeded, PR didn't
            }
        };

        PrPublisher.PrResult result = new PrPublisher(host, (key) -> Optional.empty())
                .publish(new PrPublisher.PrRequest(work, "ciam-tests", "veritas/gen", "main", "t", "d", "msg"));

        // The branch is returned (so the caller persists it) with a null PR url — not an exception that loses it.
        assertThat(result.branch()).isEqualTo("veritas/gen");
        assertThat(result.prUrl()).isNull();
        try (Git origin = Git.open(bare.toFile())) {
            assertThat(origin.branchList().call().stream()
                    .anyMatch(r -> r.getName().equals("refs/heads/veritas/gen"))).isTrue();
        }
    }
}
