package ca.bnc.qe.veritas.codegen;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;
import ca.bnc.qe.veritas.config.ConnectionsProperties;
import ca.bnc.qe.veritas.secret.SecretProvider;
import ca.bnc.qe.veritas.vcs.GitHost;
import ca.bnc.qe.veritas.vcs.RepoInfo;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.storage.file.WindowCacheConfig;
import org.eclipse.jgit.transport.PushResult;
import org.eclipse.jgit.transport.RemoteRefUpdate;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Exercises the full JGit publish path (branch → commit → push) against a local bare remote — no network,
 * no credentials — and verifies the PR is opened via the {@link GitHost} with the pushed branch.
 */
class PrPublisherTest {

    // These tests clone/fetch real git repos. On Windows a JGit pack-file handle can linger past close, which makes
    // JUnit's built-in @TempDir cleanup fail the test on a filesystem quirk. We self-manage the temp dir instead and
    // clean it best-effort (deleteQuietly), so a lingering pack never turns a passing test red. No-op cost on Linux.
    private Path tmp;

    @BeforeAll
    static void disablePackMemoryMapping() {
        // A memory-mapped pack can't be deleted on Windows until GC unmaps it (non-deterministic). Reading packs
        // WITHOUT mmap keeps handles promptly closeable so the cleanup below deletes almost everything each run.
        WindowCacheConfig cfg = new WindowCacheConfig();
        cfg.setPackedGitMMAP(false);
        cfg.install();
    }

    @BeforeEach
    void makeTempDir() throws IOException {
        tmp = Files.createTempDirectory("veritas-prpublisher-");
    }

    @AfterEach
    void cleanTempDir() throws IOException {
        deleteQuietly(tmp);
    }

    @Test
    void pushesBranchToRemoteAndOpensPr() throws Exception {
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();

        Path work = tmp.resolve("work");
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString())
                .setDirectory(work.toFile()).call()) {
            Files.writeString(work.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }

        // a generated test file the publisher should commit
        Files.writeString(work.resolve("GeneratedApiTest.java"), "class GeneratedApiTest {}");

        String[] capturedBranch = new String[1];
        GitHost host = new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) {
                return List.of();
            }
            public List<String> listBranches(String appId, String repoSlug) {
                return List.of();
            }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) {
                return null;
            }
            public String openPullRequest(String repoSlug, String sourceBranch, String targetBranch,
                                          String title, String description) {
                capturedBranch[0] = sourceBranch;
                return "https://bitbucket.org/bnc/" + repoSlug + "/pull-requests/1";
            }
        };
        SecretProvider secrets = key -> Optional.empty();

        PrPublisher publisher = new PrPublisher(host, secrets, conns("SERVER_DC"));   // Bearer-auth branch (PAT)
        PrPublisher.PrResult result = publisher.publish(new PrPublisher.PrRequest(
                work, "ciam-policies-tests", "veritas/generated-tests", "main",
                "Add generated API tests", "Generated by Veritas", "test: add generated API tests"));

        assertThat(result.branch()).isEqualTo("veritas/generated-tests");
        assertThat(result.prUrl()).contains("/pull-requests/1");
        assertThat(capturedBranch[0]).isEqualTo("veritas/generated-tests");

        // the branch must exist on the bare remote
        try (Git origin = Git.open(bare.toFile())) {
            boolean pushed = origin.branchList().call().stream()
                    .anyMatch(r -> r.getName().equals("refs/heads/veritas/generated-tests"));
            assertThat(pushed).isTrue();
        }
    }

    @Test
    void returnsThePushedBranchAsABreadcrumbWhenOpeningThePrFails() throws Exception {
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        Path work = tmp.resolve("work");
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(work.toFile()).call()) {
            Files.writeString(work.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }
        Files.writeString(work.resolve("GeneratedApiTest.java"), "class GeneratedApiTest {}");

        GitHost host = new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) { return List.of(); }
            public List<String> listBranches(String appId, String repoSlug) { return List.of(); }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) { return null; }
            public String openPullRequest(String r, String s, String t, String ti, String d) {
                throw new IllegalStateException("Bitbucket PR creation failed");   // push succeeded, PR didn't
            }
        };

        PrPublisher.PrResult result = new PrPublisher(host, (key) -> Optional.empty(), conns("SERVER_DC"))
                .publish(new PrPublisher.PrRequest(work, "ciam-tests", "veritas/gen", "main", "t", "d", "msg"));

        // The branch is returned (so the caller persists it) with a null PR url — not an exception that loses it.
        assertThat(result.branch()).isEqualTo("veritas/gen");
        assertThat(result.prUrl()).isNull();
        try (Git origin = Git.open(bare.toFile())) {
            assertThat(origin.branchList().call().stream()
                    .anyMatch(r -> r.getName().equals("refs/heads/veritas/gen"))).isTrue();
        }
    }

    @Test
    void pushesWithBasicAuthOnCloudEdition() throws Exception {
        // Cloud (and explicit BASIC) uses username + token — the Bearer path is Server/DC-only. Proves the auth
        // choice is edition-aware (the bug was: push always Basic, so a Server/DC PAT push 401'd while clone worked).
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        Path work = tmp.resolve("work");
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(work.toFile()).call()) {
            Files.writeString(work.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }
        Files.writeString(work.resolve("GeneratedApiTest.java"), "class GeneratedApiTest {}");
        GitHost host = new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) { return List.of(); }
            public List<String> listBranches(String appId, String repoSlug) { return List.of(); }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) { return null; }
            public String openPullRequest(String r, String s, String t, String ti, String d) {
                return "https://bitbucket.org/bnc/" + r + "/pull-requests/1";
            }
        };

        PrPublisher.PrResult result = new PrPublisher(host, (key) -> Optional.empty(), conns("CLOUD"))
                .publish(new PrPublisher.PrRequest(work, "ciam-tests", "veritas/gen-cloud", "main", "t", "d", "msg"));

        assertThat(result.branch()).isEqualTo("veritas/gen-cloud");
        try (Git origin = Git.open(bare.toFile())) {
            assertThat(origin.branchList().call().stream()
                    .anyMatch(r -> r.getName().equals("refs/heads/veritas/gen-cloud"))).isTrue();
        }
    }

    @Test
    void aSecondFixForTheSameBranchAccumulatesInsteadOfClobberingTheFirst() throws Exception {
        // The per-(Jira key, project) branch means two fix trains for the same ticket+project push the SAME branch.
        // Each train clones fresh from develop, so a blind force-push by the second would ERASE the first's commit.
        // The publisher must fetch+merge the existing branch so BOTH fixes survive on it.
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        seedRemote(bare, tmp.resolve("seed"));

        PrPublisher publisher = new PrPublisher(noopHost(), key -> Optional.empty(), conns("SERVER_DC"));
        String branch = "feature/LSIST-439-snyk-fix-app-7488";

        // First fix train: a fresh clone that bumps dependency A.
        Path w1 = tmp.resolve("w1");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w1.toFile()).call().close();
        Files.writeString(w1.resolve("bump-A.txt"), "commons-lang3 -> 3.18.0");
        publisher.pushBranch(w1, "lsist-bom", branch, "LSIST-439: Bump commons-lang3 to 3.18.0");

        // Second fix train for the SAME ticket+project: a DIFFERENT fresh clone off develop (no bump-A) bumps B.
        Path w2 = tmp.resolve("w2");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w2.toFile()).call().close();
        Files.writeString(w2.resolve("bump-B.txt"), "jackson -> 2.17.0");
        publisher.pushBranch(w2, "lsist-bom", branch, "LSIST-439: Bump jackson to 2.17.0");

        // The shared branch on the remote must carry BOTH bumps — the second push accumulated onto the first.
        Path check = tmp.resolve("check");
        Git.cloneRepository().setURI(bare.toUri().toString()).setBranch(branch)
                .setDirectory(check.toFile()).call().close();
        assertThat(Files.exists(check.resolve("bump-A.txt"))).as("first fix preserved").isTrue();
        assertThat(Files.exists(check.resolve("bump-B.txt"))).as("second fix added").isTrue();
    }

    @Test
    void pushBranchReturnsTheCommitShaAndTheCreatedFlag() throws Exception {
        // Part D visibility: the push reports the sha of the commit it made and whether the branch was newly created,
        // so the stepper can show "Committed abc1234… (new branch)" instead of being blind about what happened.
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        seedRemote(bare, tmp.resolve("seed"));
        PrPublisher publisher = new PrPublisher(noopHost(), key -> Optional.empty(), conns("SERVER_DC"));
        String branch = "feature/LSIST-9-snyk-fix-app-1";

        Path w1 = tmp.resolve("w1");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w1.toFile()).call().close();
        Files.writeString(w1.resolve("fix.txt"), "bump");
        PrPublisher.PushOutcome first = publisher.pushBranch(w1, "lsist-bom", branch, "LSIST-9: bump");
        assertThat(first.branch()).isEqualTo(branch);
        assertThat(first.commitSha()).as("a real 40-char git sha").hasSize(40);
        assertThat(first.created()).as("a brand-new branch").isTrue();

        // A second push to the SAME branch accumulates onto the existing remote branch → created=false, own sha.
        Path w2 = tmp.resolve("w2");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w2.toFile()).call().close();
        Files.writeString(w2.resolve("fix2.txt"), "bump2");
        PrPublisher.PushOutcome second = publisher.pushBranch(w2, "lsist-bom", branch, "LSIST-9: bump2");
        assertThat(second.created()).as("accumulated onto an existing branch, not created").isFalse();
        assertThat(second.commitSha()).hasSize(40);
    }

    @Test
    void concurrentPushesToTheSameBranchBothSurviveInsteadOfClobbering() throws Exception {
        // Bulk: several trains resolve to the SAME (repoSlug, branch) and push at the same time. Without the per-branch
        // lock, both could see the branch as new, both force-push, and the later clobbers the earlier. With it, they
        // serialize and the second ACCUMULATES — both fixes survive.
        Path bare = tmp.resolve("origin.git");
        Git.init().setBare(true).setDirectory(bare.toFile()).call().close();
        seedRemote(bare, tmp.resolve("seed"));
        PrPublisher publisher = new PrPublisher(noopHost(), key -> Optional.empty(), conns("SERVER_DC"));
        String branch = "feature/LSIST-1-snyk-fix-app-7488";

        Path w1 = tmp.resolve("w1");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w1.toFile()).call().close();
        Files.writeString(w1.resolve("fix-A.txt"), "bump A");
        Path w2 = tmp.resolve("w2");
        Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(w2.toFile()).call().close();
        Files.writeString(w2.resolve("fix-B.txt"), "bump B");

        ExecutorService pool = Executors.newFixedThreadPool(2);
        CountDownLatch start = new CountDownLatch(1);   // release both at once to force the race
        Future<?> f1 = pool.submit(() -> push(publisher, start, w1, branch, "LSIST-1: A"));
        Future<?> f2 = pool.submit(() -> push(publisher, start, w2, branch, "LSIST-1: B"));
        start.countDown();
        f1.get(60, TimeUnit.SECONDS);
        f2.get(60, TimeUnit.SECONDS);
        pool.shutdownNow();

        Path check = tmp.resolve("check");
        Git.cloneRepository().setURI(bare.toUri().toString()).setBranch(branch).setDirectory(check.toFile()).call().close();
        assertThat(Files.exists(check.resolve("fix-A.txt"))).as("first fix survived the race").isTrue();
        assertThat(Files.exists(check.resolve("fix-B.txt"))).as("second fix survived the race").isTrue();
    }

    private static Object push(PrPublisher publisher, CountDownLatch start, Path work, String branch, String msg) {
        try {
            start.await();
            publisher.pushBranch(work, "lsist-bom", branch, msg);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        return null;
    }

    /** Best-effort recursive delete that swallows a locked pack file (Windows keeps a JGit pack handle briefly past
     *  close); the OS temp cleaner reaps any remnant. Never fails a test on a filesystem quirk. */
    private static void deleteQuietly(Path root) throws IOException {
        if (!Files.exists(root)) {
            return;
        }
        try (Stream<Path> walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException ignored) {
                    // a pack file still mapped/held on Windows — leave it for the OS temp cleaner
                }
            });
        }
    }

    @Test
    void aRejectedRefTurnsIntoAThrownErrorCarryingTheRemoteReason() {
        // The root bug: JGit does NOT throw when Bitbucket rejects the ref (branching-model / branch-permission hook).
        // verifyPushAccepted must surface that as a real failure with the remote's own message, so "pushed" is never
        // logged for a branch Bitbucket never created.
        RemoteRefUpdate rejected = mock(RemoteRefUpdate.class);
        when(rejected.getStatus()).thenReturn(RemoteRefUpdate.Status.REJECTED_OTHER_REASON);
        when(rejected.getMessage()).thenReturn("branch name does not match the branching model");
        PushResult result = mock(PushResult.class);
        when(result.getRemoteUpdates()).thenReturn(List.of(rejected));

        assertThatThrownBy(() -> PrPublisher.verifyPushAccepted(
                List.of(result), "feature/LSIST-439-snyk-fix-app-7488", "lsist-bom"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("feature/LSIST-439-snyk-fix-app-7488")
                .hasMessageContaining("lsist-bom")
                .hasMessageContaining("REJECTED_OTHER_REASON")
                .hasMessageContaining("branching model")               // the remote's own reason is carried through
                .hasMessageContaining("branch permissions");
    }

    @Test
    void anAcceptedOrUpToDatePushIsNotFlaggedAsAFailure() {
        // OK (created/updated) and UP_TO_DATE (nothing to push, e.g. an idempotent re-run) are BOTH success — the
        // check must not turn a clean no-op push into a spurious error.
        RemoteRefUpdate ok = mock(RemoteRefUpdate.class);
        when(ok.getStatus()).thenReturn(RemoteRefUpdate.Status.OK);
        RemoteRefUpdate upToDate = mock(RemoteRefUpdate.class);
        when(upToDate.getStatus()).thenReturn(RemoteRefUpdate.Status.UP_TO_DATE);
        PushResult result = mock(PushResult.class);
        when(result.getRemoteUpdates()).thenReturn(List.of(ok, upToDate));

        assertThatCode(() -> PrPublisher.verifyPushAccepted(List.of(result), "feature/x", "repo"))
                .doesNotThrowAnyException();
    }

    /** Give the bare remote an initial commit on its default branch (the base the fix branches fork from). */
    private static void seedRemote(Path bare, Path seedWork) throws Exception {
        try (Git git = Git.cloneRepository().setURI(bare.toUri().toString()).setDirectory(seedWork.toFile()).call()) {
            Files.writeString(seedWork.resolve("README.md"), "seed");
            git.add().addFilepattern(".").call();
            git.commit().setMessage("seed").setAuthor("t", "t@t").setCommitter("t", "t@t").call();
            git.push().setRemote("origin").call();
        }
    }

    /** A GitHost whose methods are never exercised — {@code pushBranch} doesn't touch the host. */
    private static GitHost noopHost() {
        return new GitHost() {
            public List<RepoInfo> discoverRepos(String appId) { return List.of(); }
            public List<String> listBranches(String appId, String repoSlug) { return List.of(); }
            public Path clone(RepoInfo repo, String branch, Path destinationParent) { return null; }
            public String openPullRequest(String r, String s, String t, String ti, String d) { return null; }
        };
    }

    private static ConnectionsProperties conns(String edition) {
        ConnectionsProperties c = new ConnectionsProperties();
        c.getBitbucket().setEdition(edition);
        return c;
    }
}
