package ca.bnc.qe.veritas.llm;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * Local/dev/test gateway. Active by default ({@code veritas.llm.mode=mock}) so the whole pipeline runs
 * without the {@code copilot} CLI. Returns a deterministic, schema-valid response for the Phase-0 echo
 * skill; later phases register richer canned responses keyed by prompt content.
 */
@Component
@ConditionalOnProperty(name = "veritas.llm.mode", havingValue = "mock", matchIfMissing = true)
@Slf4j
public class MockLlmGateway implements LlmGateway {

    @Override
    public boolean isAvailable() {
        return true;
    }

    @Override
    public String complete(String prompt, String model) {
        log.debug("MockLlmGateway.complete (model={}, promptChars={})", model, prompt == null ? 0 : prompt.length());
        if (prompt != null && prompt.contains("[TRANSLATE]")) {
            // Mock can't translate; return an empty map so the service falls back to English (a real run uses
            // the cheapest Copilot model). Keeps the report bilingual-capable without a real LLM in tests.
            return "Translations (mock).\n```json\n{}\n```\n";
        }
        if (prompt != null && prompt.contains("[TEST-STRATEGY]")) {
            return """
                    Test strategy (mock — a real run uses Copilot).

                    ```json
                    {"markdown": "# Test Strategy (mock)\\n\\n## Scope\\n## Test levels\\n## Risk-based prioritization\\n## Entry & exit criteria\\n", "summary": "mock strategy", "riskRegister": [{"id": "R1", "description": "Auth bypass on policy APIs", "level": "HIGH", "citation": "CTAL-TM §1.3"}], "testApproach": {"levels": ["System", "Integration"], "types": ["Functional", "Security"]}, "exitCriteria": [{"criterion": "All HIGH risks have >=2 tests", "metric": "risk coverage %", "citation": "CTAL-TM §1.4.3"}], "selfReview": {"confidence": 80, "blindSpots": ["No performance NFRs supplied"]}}
                    ```
                    """;
        }
        if (prompt != null && prompt.contains("[IMPLEMENT-TESTS]")) {
            return """
                    Generated tests (mock).

                    ```json
                    {"files": [{"path": "src/test/java/GeneratedApiTest.java", "content": "// generated by Veritas (mock)\\nclass GeneratedApiTest {}\\n"}], "todos": ["Set the base URL in serverConfig.json"]}
                    ```
                    """;
        }
        if (prompt != null && prompt.contains("[TEST-PLAN]")) {
            // Structured, consultant-grade deliverable (mock — a real run uses Copilot). Keeps the two
            // required-case titles the coverage matcher/tests rely on.
            return """
                    Release test plan (mock).

                    ```json
                    {"executiveSummary":"Release 8.2 carries elevated risk in policy creation and authorized retrieval; risk-based testing prioritizes input-validation and authZ coverage.","scope":{"inScope":["Policy create/read APIs"],"outOfScope":["Batch jobs"],"objectives":["Validate functional correctness and authZ for release 8.2"],"assumptions":["Stable system test environment"]},"riskRegister":[{"id":"R1","description":"Policy creation accepts invalid payloads","category":"PRODUCT","qualityCharacteristic":"Functional suitability","likelihood":"M","impact":"H","level":"HIGH","mitigation":"BVA + decision-table coverage on create","citation":"CTAL-TM §1.3"},{"id":"R2","description":"Unauthorized read of policies","category":"PRODUCT","qualityCharacteristic":"Security","likelihood":"L","impact":"VH","level":"HIGH","mitigation":"AuthZ matrix on read","citation":"CTAL-TM §1.3"}],"testApproach":{"levels":["System","System integration"],"types":["Functional","Security"],"techniques":[{"name":"Boundary Value Analysis","rationale":"Bounded fields on create","citation":"CTFL §4.2.2"},{"name":"Decision Table","rationale":"Role x state rules","citation":"CTAL-TA §3.3.1"}],"entryCriteria":["Smoke tests pass","Test data provisioned"]},"exitCriteria":[{"criterion":"Every HIGH risk has >=2 executed cases","metric":"risk coverage %","smart":true,"citation":"CTAL-TM §1.4.3"},{"criterion":"No open CRITICAL defects","metric":"open critical count = 0","smart":true,"citation":"CTAL-TM §1.4.3"}],"estimation":{"technique":"three-point","effortDays":12,"basis":"E=(a+4m+b)/6 over 2 epics","citation":"CTFL §5.1.4"},"requiredCases":[{"title":"Validate create policy","technique":"Boundary Value Analysis","priority":"P1","level":"System","type":"Functional","requirementKey":"CIAM-1","riskId":"R1","citation":"CTFL §4.2.2"},{"title":"Validate get policy","technique":"Decision Table","priority":"P1","level":"System","type":"Security","requirementKey":"CIAM-2","riskId":"R2","citation":"CTAL-TA §3.3.1"}],"selfReview":{"confidence":84,"rubricChecks":[{"check":"Every required case traces to a requirement and a risk","pass":true,"note":"CIAM-1->R1, CIAM-2->R2"},{"check":"Exit criteria S.M.A.R.T.","pass":true,"note":"both measurable"}],"blindSpots":["Non-functional performance thresholds were not supplied in the basis"]},"markdown":"# Release Test Plan — fixVersion 8.2 (mock)\\n\\nExecutive summary, risk register, RTM, and S.M.A.R.T. exit criteria are carried in the structured fields and rendered by the dashboard."}
                    ```
                    """;
        }
        if (prompt != null && prompt.contains("[TEST-CASES]")) {
            return """
                    Test cases (mock).

                    ```json
                    {"cases": [{"title": "Validate happy path", "technique": "Equivalence Partitioning", "priority": "P1", "type": "Functional", "rationale": "EP covers the valid input partition (CTFL §4.2.1)", "requirementKey": "CIAM-1", "steps": [{"action": "Call endpoint", "data": "valid", "expected": "200"}]}], "selfReview": {"confidence": 82, "blindSpots": ["No boundary cases generated for unbounded fields"]}}
                    ```
                    """;
        }
        if (prompt != null && prompt.contains("[TEST-CASE-REVIEW]")) {
            return """
                    Review (mock).

                    ```json
                    {"score": 78, "verdict": "Solid", "gaps": [{"severity": "MAJOR", "issue": "No boundary cases", "cite": "CTAL-TA 3"}], "rubric": [{"criterion": "C1 coverage", "score": 3, "note": "missing BVA"}, {"criterion": "C2 clarity", "score": 4, "note": "ok"}], "correctedSteps": [{"action": "Call endpoint", "data": "boundary", "expected": "400"}], "selfReview": {"confidence": 76, "blindSpots": ["Could not see linked requirement"]}}
                    ```
                    """;
        }
        if (prompt != null && prompt.contains("[CONTRACT-RECONCILE]")) {
            // Deterministic, schema-valid stand-in for the real Copilot reconcile reply.
            return """
                    Contract reconciliation (mock — a real run uses Copilot).

                    ```json
                    {"correctedYaml": "# corrected OpenAPI (mock placeholder — real run generates the reconciled spec)\\n", "findings": [], "designFindings": [{"layer": "L5", "severity": "MINOR", "endpoint": null, "summary": "Inconsistent resource naming across endpoints", "explanation": "Mixed singular/plural nouns reduce API clarity.", "citation": "CTAL-TA §4"}, {"layer": "L6", "severity": "MAJOR", "endpoint": null, "summary": "Spec is a weak test basis — no examples, constraints, or error responses", "explanation": "Without these, equivalence/boundary cases cannot be derived from the spec.", "citation": "CTFL §2"}], "selfReview": {"confidence": 79, "blindSpots": ["Runtime-only routes and security filters not visible to static analysis"]}}
                    ```
                    """;
        }
        return """
                Echo complete.

                ```json
                {"message": "echo ok"}
                ```
                """;
    }
}
