package ca.bnc.qe.veritas.defect;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import ca.bnc.qe.veritas.config.ConnectionsProperties;
import ca.bnc.qe.veritas.integration.jira.JiraCreateRequest;
import ca.bnc.qe.veritas.persistence.FindingRecord;
import org.springframework.stereotype.Component;

/**
 * Builds the Jira defect payload from a finding (pure, testable). Title = "service — endpoint — problem".
 * For Jira Server/DC (the default) the description is <b>wiki markup</b> with {@code {code:yaml}} /
 * {@code {code:java}} blocks (matching the BNC contract-validator template); for Cloud it stays plain
 * paragraphs (rendered to ADF by the Cloud client).
 */
@Component
public class DefectComposer {

    private final boolean wiki;

    @org.springframework.beans.factory.annotation.Autowired
    public DefectComposer(ConnectionsProperties connections) {
        this.wiki = connections != null && connections.getJira() != null
                && "SERVER_DC".equalsIgnoreCase(connections.getJira().getEdition());
    }

    /** Convenience for unit tests: plain-paragraph (Cloud-style) output. */
    public DefectComposer() {
        this.wiki = false;
    }

    public JiraCreateRequest compose(FindingRecord f, String serviceName, String projectKey, String issueType) {
        String problem = f.getType() == null ? "contract issue"
                : f.getType().toLowerCase(Locale.ROOT).replace('_', ' ');
        String title = nz(serviceName) + " — " + nz(f.getEndpoint()) + " — " + problem;
        List<String> paragraphs = wiki ? wikiParagraphs(f) : plainParagraphs(f);
        List<String> labels = List.of("contract-validation", "layer-" + nz(f.getLayer()), "severity-" + nz(f.getSeverity()));
        return new JiraCreateRequest(projectKey, issueType == null ? "Bug" : issueType, title, paragraphs, labels);
    }

    private List<String> plainParagraphs(FindingRecord f) {
        List<String> paragraphs = new ArrayList<>();
        if (notBlank(f.getSummary())) {
            paragraphs.add(f.getSummary());
        }
        if (notBlank(f.getExplanation())) {
            paragraphs.add(f.getExplanation());
        }
        paragraphs.add("Severity: " + nz(f.getSeverity()) + " · Layer: " + nz(f.getLayer())
                + " · Spec: " + nz(f.getSpecSource()) + " · Confidence: " + nz(f.getConfidence()));
        if (notBlank(f.getCodeFile())) {
            paragraphs.add("Evidence: " + f.getCodeFile() + (f.getCodeStartLine() != null ? ":" + f.getCodeStartLine() : ""));
        }
        if (notBlank(f.getCodeSnippet())) {
            paragraphs.add(f.getCodeSnippet());
        }
        if (notBlank(f.getCurrentYamlFragment())) {
            paragraphs.add("Current YAML: " + f.getCurrentYamlFragment());
        }
        if (notBlank(f.getProposedFix())) {
            paragraphs.add("Proposed fix: " + f.getProposedFix());
        }
        if (notBlank(f.getCitation())) {
            paragraphs.add("Reference: " + f.getCitation());
        }
        return paragraphs;
    }

    /** Wiki-markup description: headed sections + {code} blocks, mirroring the reference defect template. */
    private List<String> wikiParagraphs(FindingRecord f) {
        List<String> p = new ArrayList<>();
        if (notBlank(f.getSummary())) {
            p.add(f.getSummary());
        }
        if (notBlank(f.getExplanation())) {
            p.add(f.getExplanation());
        }
        p.add("h3. Details\n* Severity: " + nz(f.getSeverity()) + "\n* Layer: " + nz(f.getLayer())
                + "\n* Spec: " + nz(f.getSpecSource()) + "\n* Confidence: " + nz(f.getConfidence()));
        if (notBlank(f.getCodeFile())) {
            String ev = "h3. Code Evidence\nEvidence: " + f.getCodeFile()
                    + (f.getCodeStartLine() != null ? ":" + f.getCodeStartLine() : "");
            if (notBlank(f.getCodeSnippet())) {
                ev += "\n{code:java}\n" + f.getCodeSnippet() + "\n{code}";
            }
            p.add(ev);
        }
        if (notBlank(f.getCurrentYamlFragment())) {
            p.add("h3. Current YAML\n{code:yaml}\n" + f.getCurrentYamlFragment() + "\n{code}");
        }
        if (notBlank(f.getProposedFix())) {
            p.add("h3. Proposed Fix (Corrected YAML)\n{code:yaml}\n" + f.getProposedFix() + "\n{code}");
        }
        if (notBlank(f.getCitation())) {
            p.add("h3. Reference\n" + f.getCitation());
        }
        p.add("----\n_Generated by Veritas Contract Validation Agent_");
        return p;
    }

    private boolean notBlank(String s) {
        return s != null && !s.isBlank();
    }

    private String nz(String s) {
        return s == null ? "" : s;
    }
}
