package ca.bnc.qe.veritas.report;

import java.util.List;
import ca.bnc.qe.veritas.persistence.TestCondition;
import ca.bnc.qe.veritas.persistence.TestStrategy;
import org.springframework.stereotype.Component;

/**
 * Renders the <b>Test Condition List</b> — the auditable test-analysis work product (ISTQB §3.1). One row per
 * condition: id, description, the basis item it traces to, risk-aligned priority, the risk reference, the ISO 25010
 * quality characteristic, the suggested design technique, and the automation candidacy. It is a projection of the
 * persisted conditions + their source strategy, so it cannot drift from them. EN; escapes all dynamic content.
 */
@Component
public class TestConditionListRenderer {

    public String renderHtml(TestStrategy strategy, List<TestCondition> conditions) {
        String service = strategy == null ? "" : nz(strategy.getServiceName());
        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"/>")
                .append("<title>Test Condition List — ").append(esc(service))
                .append("</title><style>").append(css()).append("</style></head><body>");

        sb.append("<div class=\"hdr\"><div class=\"hd\">Test Condition List</div><div class=\"sub\">")
                .append(esc(service));
        if (strategy != null && strategy.getVersion() != null) {
            sb.append(" · derived from strategy v").append(strategy.getVersion());
        }
        sb.append(" · ").append(conditions == null ? 0 : conditions.size()).append(" condition(s)</div></div>");

        sb.append("<div class=\"content\">");
        sb.append("<p class=\"intro\">Identified during <strong>test analysis</strong> — the testable aspects of the "
                + "system (“what to test”), each traced to a basis item and a risk from the test strategy, and "
                + "tagged with an automation candidacy. Test cases (“how to test”) are designed from these.</p>");

        if (conditions == null || conditions.isEmpty()) {
            sb.append("<p class=\"empty\">No test conditions have been generated yet for this strategy.</p>");
        } else {
            sb.append("<table><thead><tr>")
                    .append(th("ID")).append(th("Description")).append(th("Source (basis item)"))
                    .append(th("Priority")).append(th("Risk")).append(th("Quality char."))
                    .append(th("Technique")).append(th("Automation")).append(th("Status"))
                    .append("</tr></thead><tbody>");
            for (TestCondition c : conditions) {
                sb.append("<tr>")
                        .append(td(nz(c.getConditionRef())))
                        .append(td(esc(nz(c.getDescription()))))
                        .append(td(esc(nz(c.getSourceBasisItem()))))
                        .append(td(esc(nz(c.getPriority()))))
                        .append(td(esc(nz(c.getRiskRef()))))
                        .append(td(esc(nz(c.getQualityCharacteristic()))))
                        .append(td(esc(nz(c.getTechnique()))))
                        .append("<td>").append(automationBadge(c.getAutomation())).append("</td>")
                        .append(td(esc(nz(c.getStatus()))))
                        .append("</tr>");
            }
            sb.append("</tbody></table>");
        }

        sb.append("<p class=\"foot\">Generated by Veritas. The conditions are a projection of the persisted "
                + "test-analysis batch and its source strategy (cannot drift). Automation candidacy is advisory — "
                + "AUTOMATED / MANUAL / CANDIDATE per condition, decided by risk × repeatability × stability.</p>");
        sb.append("</div></body></html>");
        return sb.toString();
    }

    private String automationBadge(String automation) {
        String a = automation == null ? "CANDIDATE" : automation.toUpperCase(java.util.Locale.ROOT);
        String cls = switch (a) {
            case "AUTOMATED" -> "auto";
            case "MANUAL" -> "manual";
            default -> "cand";
        };
        return "<span class=\"badge " + cls + "\">" + esc(a) + "</span>";
    }

    private String th(String s) {
        return "<th>" + esc(s) + "</th>";
    }

    private String td(String inner) {
        return "<td>" + inner + "</td>";
    }

    private String nz(String s) {
        return s == null ? "" : s;
    }

    private String esc(String s) {
        return s == null ? "" : s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }

    private String css() {
        return "body{font-family:Inter,Segoe UI,system-ui,sans-serif;color:#1a1a2e;margin:0;background:#f5f6fa;line-height:1.55}"
                + ".hdr{background:linear-gradient(135deg,#1a1a2e,#0f3460);color:#fff;padding:2rem}"
                + ".hd{font-size:1.5rem;font-weight:600}.sub{opacity:.85}"
                + ".content{max-width:1100px;margin:0 auto;padding:1.5rem 2rem}"
                + ".intro{color:#475069}.empty{color:#9aa1ae;font-style:italic}"
                + "table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e3e6eb;border-radius:8px;overflow:hidden;font-size:.86rem}"
                + "thead th{background:#0f3460;color:#fff;text-align:left;padding:.55rem .6rem;font-weight:600}"
                + "tbody td{border-top:1px solid #eef0f4;padding:.5rem .6rem;vertical-align:top}"
                + "tbody tr:nth-child(even){background:#fafbfc}"
                + ".badge{display:inline-block;padding:.1rem .45rem;border-radius:10px;font-size:.72rem;font-weight:600}"
                + ".badge.auto{background:#e6f4ea;color:#1b7f3b}.badge.manual{background:#fdecec;color:#b3261e}"
                + ".badge.cand{background:#fff4e5;color:#a8620a}"
                + ".foot{color:#9aa1ae;font-size:.78rem;margin-top:2rem;border-top:1px solid #e3e6eb;padding-top:.8rem}";
    }
}
