package ca.bnc.qe.veritas.report;

import java.util.LinkedHashMap;
import java.util.Map;
import ca.bnc.qe.veritas.persistence.TestStrategy;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

/**
 * Renders the <b>"why" document</b> for a multi-source test strategy: for each feature, its implementation status,
 * the generated sections (risk register / test approach), and — the auditable part — the <b>evidence each section
 * cited</b> (the Jira/Confluence/code unit id, a verbatim quote, and the gloss), plus the deterministic coverage
 * gaps and the quality scorecard. It is a pure projection of the persisted deliverable + scorecard, so it cannot
 * drift from the strategy, and it lets a bank review board trace every claim back to its source.
 */
@Component
public class WhyDocRenderer {

    private static final Map<String, String> STATUS_LABEL = Map.of(
            "IMPLEMENTED", "Implemented", "PARTIAL", "Partial", "PLANNED", "Planned (not built)",
            "UNDOCUMENTED", "Undocumented", "COVERAGE_GAP", "Done in Jira, not built");
    private static final Map<String, String> STATUS_CLASS = Map.of(
            "IMPLEMENTED", "ok", "PARTIAL", "warn", "PLANNED", "warn", "UNDOCUMENTED", "info", "COVERAGE_GAP", "bad");
    private static final Map<String, String> GAP_LABEL = Map.of(
            "PLANNED_NOT_IMPLEMENTED", "Specified, not built", "IMPLEMENTED_UNDOCUMENTED", "Built, unspecified",
            "COVERAGE_GAP", "Done in Jira, not built", "POSSIBLE_MISCLUSTER", "Possible mis-cluster");

    private final ObjectMapper mapper;

    public WhyDocRenderer(ObjectMapper mapper) {
        this.mapper = mapper;
    }

    /** One feature's heading info plus the (label → section node) it accumulated, in deliverable order. */
    private static final class FeatureBlock {
        String name;
        String status;
        final Map<String, JsonNode> sections = new LinkedHashMap<>();
    }

    public String renderHtml(TestStrategy strategy) {
        JsonNode d = parse(strategy.getDeliverableJson());
        JsonNode sc = parse(strategy.getScorecardJson());

        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"/><title>")
                .append("Strategy Evidence &amp; Rationale — ").append(esc(nz(strategy.getServiceName())))
                .append("</title><style>").append(css()).append("</style></head><body>");
        sb.append("<div class=\"hdr\"><div class=\"hd\">Strategy Evidence &amp; Rationale</div><div class=\"sub\">")
                .append(esc(nz(strategy.getServiceName())))
                .append(strategy.getVersion() != null ? " · v" + strategy.getVersion() : "").append("</div></div>");
        sb.append("<div class=\"content\">");
        sb.append("<p class=\"intro\">Every part of this strategy traced to the Jira / Confluence / code evidence it "
                + "was generated from — so each claim can be checked against its source.</p>");

        appendScorecard(sb, sc);

        String summary = d.path("summary").asText("");
        if (!summary.isBlank()) {
            sb.append("<p class=\"summary\">").append(esc(summary)).append("</p>");
        }

        appendFeatures(sb, collectFeatures(d));
        appendGaps(sb, d.path("gaps"));

        sb.append("<p class=\"foot\">Generated by Veritas. A projection of the strategy deliverable + scorecard "
                + "(cannot drift). Quotes are verbatim from the cited unit's redacted text.</p>");
        sb.append("</div></body></html>");
        return sb.toString();
    }

    private void appendScorecard(StringBuilder sb, JsonNode sc) {
        if (!sc.isObject() || !sc.has("verdict")) {
            return;
        }
        String verdict = sc.path("verdict").asText("");
        boolean ok = "OK".equals(verdict);
        sb.append("<section class=\"card\"><div class=\"cardhd\"><h2>Quality scorecard</h2>")
                .append("<span class=\"pill ").append(ok ? "ok" : "bad").append("\">").append(esc(verdict))
                .append(" · ").append(sc.path("confidence").asInt(0)).append("%</span></div><ul class=\"checks\">");
        for (JsonNode c : sc.path("checks")) {
            boolean passed = c.path("passed").asBoolean(false);
            sb.append("<li class=\"").append(passed ? "pass" : "fail").append("\"><span class=\"mark\">")
                    .append(passed ? "✓" : "✗").append("</span> <strong>").append(esc(c.path("name").asText("")))
                    .append("</strong> — ").append(esc(c.path("detail").asText(""))).append("</li>");
        }
        sb.append("</ul></section>");
    }

    /** Group risk-register and test-approach sections by featureId, preserving deliverable order. */
    private Map<String, FeatureBlock> collectFeatures(JsonNode d) {
        Map<String, FeatureBlock> byFeature = new LinkedHashMap<>();
        accumulate(byFeature, d.path("riskRegister"), "Risk register");
        accumulate(byFeature, d.path("testApproach"), "Test approach");
        return byFeature;
    }

    private void accumulate(Map<String, FeatureBlock> byFeature, JsonNode sections, String label) {
        for (JsonNode node : sections) {
            String featureId = node.path("featureId").asText(node.path("feature").asText(""));
            FeatureBlock block = byFeature.computeIfAbsent(featureId, k -> new FeatureBlock());
            block.name = node.path("feature").asText(block.name == null ? featureId : block.name);
            block.status = node.path("featureStatus").asText(block.status == null ? "" : block.status);
            block.sections.put(label, node);
        }
    }

    private void appendFeatures(StringBuilder sb, Map<String, FeatureBlock> byFeature) {
        if (byFeature.isEmpty()) {
            return;
        }
        sb.append("<h2 class=\"sec\">Features</h2>");
        for (FeatureBlock f : byFeature.values()) {
            sb.append("<section class=\"feat\"><div class=\"feathd\"><h3>").append(esc(nz(f.name))).append("</h3>")
                    .append(statusPill(f.status)).append("</div>");
            f.sections.forEach((label, node) -> {
                sb.append("<div class=\"part\"><div class=\"plabel\">").append(esc(label)).append("</div>");
                sb.append(renderContent(node.path("content"), 0));
                appendEvidence(sb, node.path("evidence"));
                sb.append("</div>");
            });
            sb.append("</section>");
        }
    }

    private void appendEvidence(StringBuilder sb, JsonNode evidence) {
        if (!evidence.isArray() || evidence.isEmpty()) {
            return;
        }
        sb.append("<div class=\"evidence\"><div class=\"elabel\">Cited evidence</div><ul>");
        for (JsonNode e : evidence) {
            sb.append("<li><code>").append(esc(e.path("unitId").asText(""))).append("</code> ")
                    .append("<span class=\"quote\">“").append(esc(e.path("quote").asText(""))).append("”</span>");
            String gloss = e.path("gloss").asText("");
            if (!gloss.isBlank()) {
                sb.append(" <span class=\"gloss\">— ").append(esc(gloss)).append("</span>");
            }
            sb.append("</li>");
        }
        sb.append("</ul></div>");
    }

    private void appendGaps(StringBuilder sb, JsonNode gaps) {
        if (!gaps.isArray() || gaps.isEmpty()) {
            return;
        }
        sb.append("<h2 class=\"sec\">Coverage gaps</h2><ul class=\"gaps\">");
        for (JsonNode g : gaps) {
            String kind = g.path("kind").asText("");
            sb.append("<li><span class=\"gkind\">").append(esc(GAP_LABEL.getOrDefault(kind, kind))).append("</span> ")
                    .append(esc(g.path("message").asText(""))).append("</li>");
        }
        sb.append("</ul>");
    }

    /** Render arbitrary LLM section content as readable nested HTML (objects → labelled rows, arrays → bullets). */
    private String renderContent(JsonNode content, int depth) {
        if (content == null || content.isMissingNode() || content.isNull() || depth > 6) {
            return "";
        }
        if (content.isValueNode()) {
            return "<span>" + esc(content.asText("")) + "</span>";
        }
        StringBuilder sb = new StringBuilder();
        if (content.isArray()) {
            sb.append("<ul class=\"content\">");
            for (JsonNode item : content) {
                sb.append("<li>").append(renderContent(item, depth + 1)).append("</li>");
            }
            sb.append("</ul>");
        } else {   // object
            sb.append("<dl class=\"content\">");
            content.fields().forEachRemaining(entry -> sb.append("<dt>").append(esc(entry.getKey())).append("</dt><dd>")
                    .append(renderContent(entry.getValue(), depth + 1)).append("</dd>"));
            sb.append("</dl>");
        }
        return sb.toString();
    }

    private String statusPill(String status) {
        String cls = STATUS_CLASS.getOrDefault(status, "info");
        String label = STATUS_LABEL.getOrDefault(status, status);
        return "<span class=\"pill " + cls + "\">" + esc(label) + "</span>";
    }

    private JsonNode parse(String json) {
        try {
            return json == null || json.isBlank() ? mapper.createObjectNode() : mapper.readTree(json);
        } catch (Exception e) {
            return mapper.createObjectNode();
        }
    }

    private static String nz(String s) {
        return s == null ? "" : s;
    }

    private static String esc(String s) {
        return s == null ? "" : s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }

    private static String css() {
        return "body{font-family:Inter,Segoe UI,system-ui,sans-serif;color:#1a1a2e;margin:0;background:#f5f6fa;line-height:1.55}"
                + ".hdr{background:linear-gradient(135deg,#1a1a2e,#0f3460);color:#fff;padding:2rem}"
                + ".hd{font-size:1.5rem;font-weight:600}.sub{opacity:.85}"
                + ".content{max-width:920px;margin:0 auto;padding:1.5rem 2rem}.intro{color:#475069}"
                + ".summary{background:#fff;border:1px solid #e3e6eb;border-radius:8px;padding:.8rem 1rem;color:#33415c}"
                + "h2.sec{font-size:1.1rem;margin:1.6rem 0 .6rem;border-bottom:1px solid #e3e6eb;padding-bottom:.3rem}"
                + ".card{background:#fff;border:1px solid #e3e6eb;border-radius:10px;padding:.9rem 1.1rem;margin-top:1rem}"
                + ".cardhd{display:flex;align-items:center;justify-content:space-between}.cardhd h2{font-size:1.05rem;margin:0}"
                + "ul.checks{list-style:none;margin:.6rem 0 0;padding:0;font-size:.88rem}"
                + "ul.checks li{margin:.25rem 0}.checks .mark{font-weight:700}.checks li.pass .mark{color:#1d9e75}"
                + ".checks li.fail .mark{color:#d83a3a}"
                + "section.feat{background:#fff;border:1px solid #e3e6eb;border-radius:10px;padding:1rem 1.25rem;margin-top:1rem}"
                + ".feathd{display:flex;align-items:center;gap:.6rem}.feathd h3{font-size:1.05rem;margin:0}"
                + ".part{margin-top:.8rem;border-top:1px dashed #e7eaef;padding-top:.6rem}"
                + ".plabel{font-weight:600;font-size:.8rem;text-transform:uppercase;letter-spacing:.04em;color:#7a8499}"
                + "dl.content{margin:.3rem 0}dl.content dt{font-weight:600;font-size:.85rem;color:#33415c;margin-top:.35rem}"
                + "dl.content dd{margin:0 0 0 .8rem;font-size:.9rem}ul.content{margin:.2rem 0 .2rem 1.1rem;font-size:.9rem}"
                + ".evidence{background:#f6f8fb;border:1px solid #e3e6eb;border-radius:8px;padding:.6rem .8rem;margin-top:.6rem}"
                + ".elabel{font-weight:600;font-size:.78rem;text-transform:uppercase;letter-spacing:.04em;color:#7a8499}"
                + ".evidence ul{margin:.3rem 0 0 0;padding:0;list-style:none}.evidence li{margin:.3rem 0;font-size:.88rem}"
                + ".evidence code{background:#e8eef6;color:#0f3460;border-radius:4px;padding:1px 5px;font-size:.82rem}"
                + ".quote{color:#33415c}.gloss{color:#7a8499}"
                + "ul.gaps{margin:.3rem 0 0;padding-left:1.1rem;font-size:.9rem}ul.gaps li{margin:.3rem 0}"
                + ".gkind{font-weight:600;color:#993c1d}"
                + ".pill{font-size:.72rem;font-weight:600;border-radius:999px;padding:2px 9px}"
                + ".pill.ok{background:#e1f5ee;color:#0f6e56}.pill.warn{background:#faeeda;color:#854f0b}"
                + ".pill.info{background:#e6f1fb;color:#0c447c}.pill.bad{background:#fceaea;color:#a32d2d}"
                + ".foot{color:#9aa1ae;font-size:.78rem;margin-top:2rem;border-top:1px solid #e3e6eb;padding-top:.8rem}";
    }
}
