package ca.bnc.qe.veritas.vcs;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.containing;
import static com.github.tomakehurst.wiremock.client.WireMock.equalTo;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import ca.bnc.qe.veritas.config.ConnectionsProperties;
import ca.bnc.qe.veritas.integration.Retries;
import ca.bnc.qe.veritas.secret.SecretProvider;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import com.github.tomakehurst.wiremock.stubbing.Scenario;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.retry.support.RetryTemplate;

/**
 * Exercises {@link BitbucketServerClient} against the Server/DC REST surface ({@code /rest/api/1.0/...}) with
 * WireMock: discoverRepos + listBranches paging/ordering, both auth types (Bearer PAT vs Basic), PR creation
 * link/id extraction, the X-AUSERNAME identity probe, and the error paths that wrap failures as
 * {@link IllegalStateException}.
 */
class BitbucketServerClientWireMockTest {

    private WireMockServer wm;
    private final ObjectMapper mapper = new ObjectMapper();
    // GIT_USERNAME -> "alice", anything else -> "tok"
    private final SecretProvider secrets = key -> Optional.of(key.equals("GIT_USERNAME") ? "alice" : "tok");
    private final Retries retries = new Retries(RetryTemplate.builder().maxAttempts(1).build());

    @BeforeEach
    void start() {
        wm = new WireMockServer(WireMockConfiguration.options().dynamicPort());
        wm.start();
    }

    @AfterEach
    void stop() {
        wm.stop();
    }

    /** Default (BEARER PAT) client pointed at WireMock, project/workspace = PROJ, trailing slash on base. */
    private BitbucketServerClient client(String authType) {
        ConnectionsProperties p = new ConnectionsProperties();
        p.getBitbucket().setBaseUrl("http://localhost:" + wm.port() + "/");   // trailing slash exercises base() trim
        p.getBitbucket().setEdition("SERVER_DC");
        p.getBitbucket().setWorkspace("PROJ");
        p.getBitbucket().setAuthType(authType);
        return new BitbucketServerClient(p, secrets, mapper, retries);
    }

    // ---------------------------------------------------------------- auth header

    @Test
    void bearerAuthHeaderIsDefaultWhenAuthTypeNull() {
        assertThat(client(null).authHeader()).isEqualTo("Bearer tok");
    }

    @Test
    void bearerAuthHeaderForBearerType() {
        assertThat(client("BEARER").authHeader()).isEqualTo("Bearer tok");
    }

    @Test
    void basicAuthHeaderEncodesUserAndToken() {
        String expected = "Basic " + Base64.getEncoder()
                .encodeToString("alice:tok".getBytes(StandardCharsets.UTF_8));
        assertThat(client("basic").authHeader()).isEqualTo(expected);   // case-insensitive match
    }

    // ---------------------------------------------------------------- URI builders

    @Test
    void buildsDiscoveryUriTrimmingTrailingSlash() {
        String uri = client("BEARER").buildDiscoveryUri("PROJ", 25);
        assertThat(uri).isEqualTo("http://localhost:" + wm.port()
                + "/rest/api/1.0/projects/PROJ/repos?limit=100&start=25");
    }

    @Test
    void buildsPullRequestUriUsingWorkspaceProjectKey() {
        String uri = client("BEARER").buildPullRequestUri("my-repo");
        assertThat(uri).isEqualTo("http://localhost:" + wm.port()
                + "/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests");
    }

    // ---------------------------------------------------------------- PR payload

    @Test
    void buildsPullRequestPayloadWithDescriptionAndTarget() throws Exception {
        String payload = client("BEARER").buildPullRequestPayload(
                "veritas/generated", "develop", "Add tests", "Generated by Veritas");
        JsonNode node = mapper.readTree(payload);
        assertThat(node.path("title").asText()).isEqualTo("Add tests");
        assertThat(node.path("description").asText()).isEqualTo("Generated by Veritas");
        assertThat(node.path("fromRef").path("id").asText()).isEqualTo("refs/heads/veritas/generated");
        assertThat(node.path("toRef").path("id").asText()).isEqualTo("refs/heads/develop");
    }

    @Test
    void buildsPullRequestPayloadOmitsBlankDescriptionAndTarget() throws Exception {
        String payload = client("BEARER").buildPullRequestPayload(
                "feature/x", "  ", "Just a title", "   ");
        JsonNode node = mapper.readTree(payload);
        assertThat(node.path("title").asText()).isEqualTo("Just a title");
        assertThat(node.has("description")).isFalse();   // blank description dropped
        assertThat(node.path("fromRef").path("id").asText()).isEqualTo("refs/heads/feature/x");
        assertThat(node.has("toRef")).isFalse();          // blank targetBranch dropped
    }

    @Test
    void buildsPullRequestPayloadNullDescriptionAndTargetOmitted() throws Exception {
        String payload = client("BEARER").buildPullRequestPayload("feature/y", null, "T", null);
        JsonNode node = mapper.readTree(payload);
        assertThat(node.has("description")).isFalse();
        assertThat(node.has("toRef")).isFalse();
        assertThat(node.path("fromRef").path("id").asText()).isEqualTo("refs/heads/feature/y");
    }

    // ---------------------------------------------------------------- discoverRepos

    @Test
    void discoverReposParsesHttpCloneUrlAndProjectKey() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos")).willReturn(aResponse()
                .withHeader("Content-Type", "application/json")
                .withBody("{\"isLastPage\":true,\"values\":[{"
                        + "\"slug\":\"ciam-policies\",\"name\":\"CIAM Policies\","
                        + "\"description\":\"policy tests\",\"defaultBranch\":\"refs/heads/master\","
                        + "\"project\":{\"key\":\"PROJ\"},\"updatedDate\":\"123\","
                        + "\"links\":{\"clone\":["
                        + "{\"name\":\"ssh\",\"href\":\"ssh://git@host/proj/repo.git\"},"
                        + "{\"name\":\"http\",\"href\":\"http://host/scm/proj/repo.git\"}]}}]}")));

        List<RepoInfo> repos = client("BEARER").discoverRepos("PROJ");

        assertThat(repos).hasSize(1);
        RepoInfo r = repos.get(0);
        assertThat(r.slug()).isEqualTo("ciam-policies");
        assertThat(r.name()).isEqualTo("CIAM Policies");
        assertThat(r.description()).isEqualTo("policy tests");
        assertThat(r.defaultBranch()).isEqualTo("refs/heads/master");
        assertThat(r.cloneUrl()).isEqualTo("http://host/scm/proj/repo.git");
        assertThat(r.projectKey()).isEqualTo("PROJ");
        assertThat(r.updatedOn()).isEqualTo("123");
        // Bearer PAT must be sent as the Authorization header
        wm.verify(getRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos"))
                .withHeader("Authorization", equalTo("Bearer tok")));
    }

    @Test
    void discoverReposPrefersHttpsCloneAndFallsBackToProjectKeyArg() {
        // no "project.key" node -> falls back to the appId argument; https clone selected; slug falls back to name
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/FALLBACK/repos")).willReturn(aResponse()
                .withHeader("Content-Type", "application/json")
                .withBody("{\"isLastPage\":true,\"values\":[{"
                        + "\"name\":\"named-only\","
                        + "\"links\":{\"clone\":["
                        + "{\"name\":\"https\",\"href\":\"https://host/scm/x/y.git\"}]}}]}")));

        List<RepoInfo> repos = client("BEARER").discoverRepos("FALLBACK");

        assertThat(repos).hasSize(1);
        assertThat(repos.get(0).slug()).isEqualTo("named-only");   // slug missing -> name
        assertThat(repos.get(0).cloneUrl()).isEqualTo("https://host/scm/x/y.git");
        assertThat(repos.get(0).projectKey()).isEqualTo("FALLBACK");
    }

    @Test
    void discoverReposPagesUsingNextPageStartAndBasicAuth() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos")).inScenario("repo-paging")
                .whenScenarioStateIs(Scenario.STARTED)
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":false,\"nextPageStart\":2,\"values\":["
                                + "{\"slug\":\"r1\"},{\"slug\":\"r2\"}]}"))
                .willSetStateTo("page2"));
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos")).inScenario("repo-paging")
                .whenScenarioStateIs("page2")
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":true,\"values\":[{\"slug\":\"r3\"}]}")));

        List<RepoInfo> repos = client("BASIC").discoverRepos("PROJ");

        assertThat(repos).extracting(RepoInfo::slug).containsExactly("r1", "r2", "r3");
        wm.verify(2, getRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos")));
        // BASIC auth path: Authorization is a Base64 Basic credential, not Bearer
        String expected = "Basic " + Base64.getEncoder()
                .encodeToString("alice:tok".getBytes(StandardCharsets.UTF_8));
        wm.verify(getRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos"))
                .withHeader("Authorization", equalTo(expected)));
    }

    @Test
    void discoverReposWrapsHttpErrorAsIllegalState() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos"))
                .willReturn(aResponse().withStatus(500).withBody("boom")));

        assertThatThrownBy(() -> client("BEARER").discoverRepos("PROJ"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server discovery failed for project 'PROJ'");
    }

    // ---------------------------------------------------------------- listBranches

    @Test
    void listBranchesPutsDefaultBranchFirstAndUsesAppIdAsProject() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/ABC/repos/my-repo/branches"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":true,\"values\":["
                                + "{\"displayId\":\"feature/a\",\"isDefault\":false},"
                                + "{\"displayId\":\"master\",\"isDefault\":true},"
                                + "{\"displayId\":\"feature/b\",\"isDefault\":false}]}")));

        // appId "ABC" overrides the configured workspace "PROJ" as the project key
        List<String> branches = client("BEARER").listBranches("ABC", "my-repo");

        assertThat(branches).containsExactly("master", "feature/a", "feature/b");
    }

    @Test
    void listBranchesFallsBackToWorkspaceWhenAppIdBlankAndUsesIdWhenNoDisplayId() {
        // blank appId -> project() == workspace "PROJ"
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/repo2/branches"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":true,\"values\":["
                                + "{\"id\":\"refs/heads/only-id\"},"   // no displayId -> uses id
                                + "{\"displayId\":\"main\",\"isDefault\":false}]}")));

        List<String> branches = client("BEARER").listBranches("  ", "repo2");

        // no default branch -> original order preserved, id used as name for the first entry
        assertThat(branches).containsExactly("refs/heads/only-id", "main");
    }

    @Test
    void listBranchesPagesAcrossEnvelopes() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/r/branches")).inScenario("branch-paging")
                .whenScenarioStateIs(Scenario.STARTED)
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":false,\"nextPageStart\":100,\"values\":["
                                + "{\"displayId\":\"b1\"}]}"))
                .willSetStateTo("p2"));
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/r/branches")).inScenario("branch-paging")
                .whenScenarioStateIs("p2")
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"isLastPage\":true,\"values\":[{\"displayId\":\"b2\",\"isDefault\":true}]}")));

        List<String> branches = client("BEARER").listBranches("PROJ", "r");

        // b2 is default -> moved to front; both pages traversed
        assertThat(branches).containsExactly("b2", "b1");
        wm.verify(2, getRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/r/branches")));
    }

    @Test
    void listBranchesWrapsHttpErrorAsIllegalState() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/bad/branches"))
                .willReturn(aResponse().withStatus(404)));

        assertThatThrownBy(() -> client("BEARER").listBranches("PROJ", "bad"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server branch listing failed for 'bad'");
    }

    // ---------------------------------------------------------------- openPullRequest

    @Test
    void openPullRequestReturnsSelfLinkHrefWhenPresent() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"id\":42,\"links\":{\"self\":[{\"href\":\"http://host/pr/42\"}]}}")));

        String result = client("BEARER").openPullRequest("my-repo", "feature/x", "master",
                "Title", "Desc");

        assertThat(result).isEqualTo("http://host/pr/42");
        wm.verify(postRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .withHeader("Authorization", equalTo("Bearer tok"))
                .withHeader("Content-Type", equalTo("application/json")));
    }

    @Test
    void openPullRequestFallsBackToIdWhenSelfLinkMissing() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"id\":\"99\",\"links\":{}}")));   // self array absent -> id used

        String result = client("BEARER").openPullRequest("my-repo", "feature/x", "master",
                "Title", null);

        assertThat(result).isEqualTo("99");
    }

    @Test
    void openPullRequestFallsBackToIdWhenSelfArrayEmpty() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"id\":\"7\",\"links\":{\"self\":[]}}")));   // empty array -> id used

        String result = client("BEARER").openPullRequest("my-repo", "feature/x", "master", "T", "D");

        assertThat(result).isEqualTo("7");
    }

    @Test
    void openPullRequestWrapsHttpErrorAsIllegalState() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .willReturn(aResponse().withStatus(409).withBody("conflict")));

        assertThatThrownBy(() -> client("BEARER").openPullRequest("my-repo", "f", "m", "T", "D"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server PR creation failed for 'my-repo'");
    }

    @Test
    void buildsPullRequestPayloadWithReviewers() throws Exception {
        String payload = client("BEARER").buildPullRequestPayload(
                "veritas/snyk-fix", "develop", "Bump jackson", "Snyk fix", List.of("alice", "bob"));
        JsonNode node = mapper.readTree(payload);
        assertThat(node.path("reviewers")).hasSize(2);
        assertThat(node.path("reviewers").get(0).path("user").path("name").asText()).isEqualTo("alice");
        assertThat(node.path("reviewers").get(1).path("user").path("name").asText()).isEqualTo("bob");
    }

    @Test
    void openPullRequestSpecTargetsGivenProjectAndSendsReviewers() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/APP7488/repos/lsist-test-framework-bom/pull-requests"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"id\":7,\"links\":{\"self\":[{\"href\":\"http://host/pr/7\"}]}}")));

        String result = client("BEARER").openPullRequest(new GitHost.PullRequestSpec(
                "APP7488", "lsist-test-framework-bom", "veritas/snyk-fix", "develop",
                "Bump jackson", "Snyk fix", List.of("alice")));

        assertThat(result).isEqualTo("http://host/pr/7");
        wm.verify(postRequestedFor(
                urlPathEqualTo("/rest/api/1.0/projects/APP7488/repos/lsist-test-framework-bom/pull-requests"))
                .withRequestBody(containing("\"reviewers\"")).withRequestBody(containing("alice")));
    }

    @Test
    void openPullRequestSpecFallsBackToConfiguredProjectWhenBlank() {
        wm.stubFor(post(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests"))
                .willReturn(aResponse().withHeader("Content-Type", "application/json")
                        .withBody("{\"id\":8,\"links\":{}}")));

        String result = client("BEARER").openPullRequest(new GitHost.PullRequestSpec(
                "  ", "my-repo", "f", "m", "T", "D", List.of()));

        assertThat(result).isEqualTo("8");
        wm.verify(postRequestedFor(urlPathEqualTo("/rest/api/1.0/projects/PROJ/repos/my-repo/pull-requests")));
    }

    // ---------------------------------------------------------------- whoAmI

    @Test
    void whoAmIReturnsUserFromHeader() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/repos"))
                .willReturn(aResponse().withHeader("X-AUSERNAME", "svc-veritas").withStatus(200)));

        assertThat(client("BEARER").whoAmI()).isEqualTo("svc-veritas");
        wm.verify(getRequestedFor(urlPathEqualTo("/rest/api/1.0/repos"))
                .withHeader("Authorization", equalTo("Bearer tok")));
    }

    @Test
    void whoAmIThrowsWhenHeaderMissing() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/repos"))
                .willReturn(aResponse().withStatus(200)));   // no X-AUSERNAME

        assertThatThrownBy(() -> client("BEARER").whoAmI())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server identity probe failed")
                .hasMessageContaining("not authenticated");
    }

    @Test
    void whoAmIThrowsWhenHeaderBlank() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/repos"))
                .willReturn(aResponse().withHeader("X-AUSERNAME", "  ").withStatus(200)));

        assertThatThrownBy(() -> client("BEARER").whoAmI())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server identity probe failed");
    }

    @Test
    void whoAmIWrapsHttpErrorAsIllegalState() {
        wm.stubFor(get(urlPathEqualTo("/rest/api/1.0/repos"))
                .willReturn(aResponse().withStatus(401)));

        assertThatThrownBy(() -> client("BEARER").whoAmI())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Bitbucket Server identity probe failed");
    }

    // ---------------------------------------------------------------- clone (error paths exercise both auth branches)

    @Test
    void cloneWrapsFailureForBearerAuth(@TempDir Path tmp) {
        // jgit clone against a non-git endpoint fails -> wrapped IllegalStateException; exercises BEARER transport callback
        RepoInfo repo = new RepoInfo("dead-repo", "Dead", "", "master",
                "http://localhost:" + wm.port() + "/scm/proj/dead-repo.git", "PROJ", "");

        assertThatThrownBy(() -> client("BEARER").clone(repo, "master", tmp))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Clone failed for 'dead-repo'");
    }

    @Test
    void cloneWrapsFailureForBasicAuthAndNullBranch(@TempDir Path tmp) {
        // null branch skips setBranch(); BASIC sets a UsernamePasswordCredentialsProvider; still fails -> wrapped
        RepoInfo repo = new RepoInfo("dead2", "Dead2", "", "master",
                "http://localhost:" + wm.port() + "/scm/proj/dead2.git", "PROJ", "");

        assertThatThrownBy(() -> client("BASIC").clone(repo, null, tmp))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Clone failed for 'dead2'");
    }
}
