package ca.bnc.qe.veritas.vcs;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Optional;
import ca.bnc.qe.veritas.config.ConnectionsProperties;
import ca.bnc.qe.veritas.integration.Retries;
import ca.bnc.qe.veritas.secret.SecretProvider;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.retry.support.RetryTemplate;

class BitbucketCloudClientTest {

    private BitbucketCloudClient client(String authType) {
        ConnectionsProperties props = new ConnectionsProperties();
        props.getBitbucket().setBaseUrl("https://api.bitbucket.org/");
        props.getBitbucket().setWorkspace("bnc");
        props.getBitbucket().setAuthType(authType);
        SecretProvider secrets = key -> Optional.of(key.equals("GIT_USERNAME") ? "user" : "tok");
        return new BitbucketCloudClient(props, secrets, new ObjectMapper(),
                new Retries(RetryTemplate.builder().maxAttempts(1).build()));
    }

    @Test
    void buildsProjectScopedDiscoveryUri() {
        String uri = client("APP_PASSWORD").buildDiscoveryUri("APP7571");
        assertThat(uri).startsWith("https://api.bitbucket.org/2.0/repositories/bnc?q=");
        assertThat(uri).contains("pagelen=100");
        assertThat(uri).contains("project.key");
        assertThat(uri).contains("APP7571");
    }

    @Test
    void basicAuthHeaderForAppPassword() {
        assertThat(client("APP_PASSWORD").authHeader()).startsWith("Basic ");
    }

    @Test
    void bearerAuthHeaderForOauth() {
        assertThat(client("OAUTH").authHeader()).isEqualTo("Bearer tok");
    }

    @Test
    void buildsPullRequestUriAndPayload() throws Exception {
        BitbucketCloudClient c = client("APP_PASSWORD");
        assertThat(c.buildPullRequestUri("ciam-policies-tests"))
                .isEqualTo("https://api.bitbucket.org/2.0/repositories/bnc/ciam-policies-tests/pullrequests");

        String payload = c.buildPullRequestPayload("veritas/generated-tests", "main",
                "Add generated API tests", "Generated by Veritas");
        com.fasterxml.jackson.databind.JsonNode node = new ObjectMapper().readTree(payload);
        assertThat(node.path("title").asText()).isEqualTo("Add generated API tests");
        assertThat(node.path("source").path("branch").path("name").asText()).isEqualTo("veritas/generated-tests");
        assertThat(node.path("destination").path("branch").path("name").asText()).isEqualTo("main");
        assertThat(node.path("description").asText()).isEqualTo("Generated by Veritas");
    }
}
